# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dimond-prediction-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dimondprediction.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_de834ceb8da04c6cbc8c4d05a2f6e2fb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_446046ec255844e29ab33107443db816 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dimondprediction.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_de834ceb8da04c6cbc8c4d05a2f6e2fb }}/helloapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dimond-prediction-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e2eb2b41625047ada82a88a948e04525 }}
        images: 'dimondprediction.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_de834ceb8da04c6cbc8c4d05a2f6e2fb }}/helloapp:${{ github.sha }}'